name: Check code with eslint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:    
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: "16"
          check-latest: true      
      - name: Check
        run: |
            npm ci
            npm run lint-diff        
          
      - name: Run pwd
        run: pwd
        
      - name: Run ls -al
        run: ls -al          
